security:
    role_hierarchy:
        ROLE_AGENT: ~
        ROLE_ADMIN: [ ROLE_AGENT ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]
        ROLE_CUSTOMER: ~
    providers:
        user_provider:
            #id: user.provider
            id: App\Security\UserProvider
        uv_api_credentials:
            id: Webkul\UVDesk\ApiBundle\Providers\ApiCredentials
    encoders:
        Webkul\UVDesk\CoreFrameworkBundle\Entity\User: auto
    firewalls:
        back_support:
            pattern: /%uvdesk_site_path.member_prefix%
            provider: user_provider
            anonymous: false
            sso:
                always_use_default_target_path: true
                default_target_path: %idp_url%/de/%uvdesk_site_path.member_prefix%/dashboard
                check_path: /de/%uvdesk_site_path.member_prefix%/otp/validate # Same as in app/config/routing.yml
                require_previous_session: false
                sso_failure_path: '%idp_login_url%' # Can also be as an absolute path to service provider
                sso_scheme: '%sso_scheme%' # Required
                sso_host: '%sso_host%' # Required
                sso_path: '%sso_path%' # SSO endpoint on IdP.
                sso_login_required: 1 # Optional
                sso_login_required_parameter: login_required # Optional
                sso_otp_host: '%sso_otp_host%' # Optional
                sso_otp_scheme: '%sso_otp_scheme%' # Optional
                sso_service: '%sso_service%' # Consumer name
                sso_service_extra: null            # Default service extra parameters. Optional.
                sso_service_extra_parameter: service_extra   # Parameter name. Optional
            form_login: false
            logout:
                invalidate_session: true
                path: helpdesk_member_handle_logout
                target: /de/%uvdesk_site_path.member_prefix%/sso/logout-user/%sso_service%
        customer:
            pattern: /
            provider: user_provider
            anonymous: null
            form_login:
                use_referer: true
                login_path: helpdesk_customer_login
                check_path: helpdesk_customer_login
                default_target_path: helpdesk_customer_ticket_collection
                always_use_default_target_path: true
            logout:
                path: helpdesk_customer_logout
                target: helpdesk_customer_login
        uvdesk_api:
            pattern: /api
            anonymous: true
            provider: uv_api_credentials
            guard:
                authenticators:
                    Webkul\UVDesk\ApiBundle\Security\Guards\APIGuard: Webkul\UVDesk\ApiBundle\Security\Guards\APIGuard
    access_control:
        - { path: /%uvdesk_site_path.member_prefix%/login,                              roles: [ IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/create-account,                     roles: [ IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/forgot-password,                    roles: [ IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/sso,                                roles: [ IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/update-credentials,                 roles: [ IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/mailbox/listener,                   roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.member_prefix%/,                                   roles: [ ROLE_AGENT ] }
        - { path: /%uvdesk_site_path.knowledgebase_customer_prefix%/login,              roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.knowledgebase_customer_prefix%/create-ticket,      roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.knowledgebase_customer_prefix%/forgot-password,    roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.knowledgebase_customer_prefix%/update-credentials, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: /%uvdesk_site_path.knowledgebase_customer_prefix%/,                   roles: [ ROLE_CUSTOMER ] }
        - { path: /portal-rest,                                                        roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
