monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']

        main:
            type: fingers_crossed
            action_level: debug
            excluded_http_codes: [ 400, 404 ]
            handler: groups
        groups:
            type: group
            members: [ streamed, mail ]
        streamed:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        mail:
            type: fingers_crossed
            action_level: warning
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: swift
            action_level: warning
        swift:
            type:       swift_mailer
            from_email: '%env(resolve:MONOLOG_MAIL_FROM)%'
            to_email:   '%env(resolve:MONOLOG_MAIL_TO)%'
            subject:    '%env(resolve:MONOLOG_MAIL_SUBJECT)%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
