monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: nested
            excluded_http_codes: [ 400, 404 ]
        nested:
            type: group
            level: debug
            members: [ streamed, deduplicated ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        streamed:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
        deduplicated:
            type: deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: '%env(resolve:MONOLOG_MAIL_FROM)%'
            to_email:   '%env(resolve:MONOLOG_MAIL_TO)%'
            subject:    '%env(resolve:MONOLOG_MAIL_SUBJECT)%'
            formatter:  monolog.formatter.html
            content_type: text/html
