<?php

return [
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Krtv\Bundle\SingleSignOnServiceProviderBundle\KrtvSingleSignOnServiceProviderBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Webkul\UVDesk\ApiBundle\UVDeskApiBundle::class => ['all' => true],
    Webkul\UVDesk\AutomationBundle\UVDeskAutomationBundle::class => ['all' => true],
    Webkul\UVDesk\CoreFrameworkBundle\UVDeskCoreFrameworkBundle::class => ['all' => true],
    Webkul\UVDesk\ExtensionFrameworkBundle\UVDeskExtensionFrameworkBundle::class => ['all' => true],
    Webkul\UVDesk\MailboxBundle\UVDeskMailboxBundle::class => ['all' => true],
    Webkul\UVDesk\SupportCenterBundle\UVDeskSupportCenterBundle::class => ['all' => true],
    Webmatic\DoctrineBundle\WebmaticDoctrineBundle::class => ['all' => true],
    Webmatic\FormBundle\WebmaticFormBundle::class => ['all' => true],
    Webmatic\KundeBundle\WebmaticKundeBundle::class => ['all' => true],
    Webmatic\PortalClientBundle\WebmaticPortalClientBundle::class => ['all' => true],
    Webmatic\TwigBundle\WebmaticTwigBundle::class => ['all' => true],
    Webmatic\UserBundle\WebmaticUserBundle::class => ['all' => true],
    Webmatic\UtilBundle\WebmaticUtilBundle::class => ['all' => true],
];
